baseURL = "https://pndv.github.io"
enableRobotsTXT = true
googleAnalytics= "G-M30EZEZ0B2"
locale = "en-gb"
title = "PNDV blog"
omit_header_text = true


[[menu.main]]
identifier = "posts"
name = "Posts"
title = "Posts"
url = "/posts/"
weight = 0

[params]
style = "dark"
math = true



[markup.goldmark.renderer]
unsafe = true

[params.homepage]
layout = "recent"
showRecent = true
showRecentItems = 10
cardView = true

[[params.social]]
id = "github"
name = "pndv"

[module]
[[module.imports]]
path = "github.com/nunocoracao/blowfish/v2"